config/routes.rb
EwhaNote::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'user_sessions' }

  match 'registrations/edit' => 'registrations#edit'
  match 'registrations/update' => 'registrations#update'

  resources :lectures do
    get :search, on: :collection
    resources :assessments
  end

  resources :assessments do
    get :my, on: :collection
    resources :votes, only: [:create]
  end

  resources :registrations

  root :to => 'assessments#index'

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  MIN_NUMBER_OF_ASSESSMENTS = 2

  has_many :assessments
  has_many :taggings
  after_initialize :initialize_with_defaults

  validates :provider, uniqueness: { scope: :title }

  index_prefix 'new-myungji'
  mapping do
    indexes :id, :type => 'string', :index => :not_analyzed
    indexes :title
    indexes :provider
  end

  def self.per_page
    12
  end

  def initialize_with_defaults
    self.upvote_count ||= 0
    self.downvote_count ||= 0
    self.assessment_count ||= 0
    self.hit_count ||= 0

    self.overall_score ||= 0
    self.presentation_score ||= 0
    self.workload_score ||= 0
    self.grading_score ||= 0
  end

  def update_assessment_count
    sql = <<-SQL
      SELECT
        COUNT(*) as count,
        AVG(overall_score) as overall_score,
        AVG(presentation_score) as presentation_score,
        AVG(workload_score) as workload_score,
        AVG(grading_score) as grading_score
      FROM assessments
      WHERE lecture_id = #{id}
    SQL

    aggregated = ActiveRecord::Base.connection.execute(sql).first

    if aggregated.is_a? Hash
      self.assessment_count = aggregated['count']
      self.overall_score = aggregated['overall_score']
      self.presentation_score = aggregated['presentation_score']
      self.workload_score = aggregated['workload_score']
      self.grading_score = aggregated['grading_score']
    else
      self.assessment_count = aggregated[0]
      self.overall_score = aggregated[1]
      self.presentation_score = aggregated[2]
      self.workload_score = aggregated[3]
      self.grading_score = aggregated[4]
    end

    save
  end

  def update_hit_count
    self.hit_count += 1
    save
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:search]
  before_filter :fetch_top_standings

  def index
    #@assessments = Assessment.paginate(page: params[:page] || 1)
  end

  def search
    @query = params[:query]
    @query.gsub!(/[+\-|!(){}\[\]\^"~*?:\\]/, "\\\\\\0") if @query

    if @query && @query.length > 0
      @result = Lecture.search("*#{@query}*", page: params[:page] || 1, per_page: 12, load: true)
    else
      @result = Lecture.paginate page: params[:page] || 1
    end
  end

  def show
    @lecture = Lecture.find params[:id]
    @lecture.update_hit_count

    @assessment = Assessment.new
    @assessments = @lecture.assessments.all.sort do |a2, a1|
      if a1.positive_votes_percentage == a2.positive_votes_percentage
        a1.votes.count <=> a2.votes.count
      else
        a1.positive_votes_percentage <=> a2.positive_votes_percentage
      end
    end
  end

  private
    def fetch_top_standings
      @lectures = Lecture.where('assessment_count >= ?', Lecture::MIN_NUMBER_OF_ASSESSMENTS).order('overall_score DESC, assessment_count DESC').first(3)
    end
end

app/helpers/lectures_helper.rb
# encoding=utf-8

module LecturesHelper
  def lecture_container(lecture, rank = nil)
    elements = []

    elements << (content_tag :span, '{', class: 'curly-braces')
    elements << (content_tag :span, lecture.provider, class: 'provider')
    elements << (content_tag :span, '/', class: 'separator')
    elements << (content_tag :span, lecture.title, class: 'title')
    elements << (content_tag :span, '}', class: 'curly-braces')


    if rank
      rank_element = content_tag('div', content_tag('span', rank, class: 'number').html_safe + content_tag('span', '.', class: 'tail').html_safe, class: 'rank').html_safe
      main_div = content_tag('div', elements.join('').html_safe, class: 'lecture').html_safe

      content_tag('div', rank_element + main_div, class: 'ranked-lecture').html_safe
    else
      content_tag('div', elements.join('').html_safe, class: 'lecture').html_safe
    end
  end

  def score_indicators(score)
    if score > 0
      full_star_tag = content_tag('div', '', class: 'score-stars full').html_safe
      half_star_tag = content_tag('div', '', class: 'score-stars half').html_safe

      rounded = score.round

      full_stars_count = rounded / 2
      half_star_count = rounded % 2

      elements = []

      full_stars_count.times do
        elements << full_star_tag.dup
      end

      half_star_count.times do
        elements << half_star_tag.dup
      end

      elements.join("").html_safe
    else
      content_tag(:p, '지금 투표해 보세요!', class: 'empty').html_safe
    end
  end

  def tagging_to_image_tag(tagging)
    tag = Tag.find(tagging.tag_id)
    style = "left: #{tagging.coord_x}px; top: #{tagging.coord_y}px"

    image_tag(asset_path(tag.image_file_name), class: 'tagged', style: style).html_safe
  end
end

app/views/lectures/_menu.html.erb
<div id="head_wrapper">
  <div id="login_info">
    <%= link_to 'Facebook', 'http://www.facebook.com/SMWUklassmate', class: 'label label-info' %>
    <span class="label label-success"><%= current_user.username %>님 환영합니다.</span>
    <%= link_to '[로그아웃]', destroy_user_session_path, class: 'label' %>
</div>
  <div id="search_wrapper">
    <a href="/"><div id="head_main_logo"></div></a>
    <div id="total_view"><span id="total_view_number"><%= Assessment.count %></span>&nbsp;개의 강의평이 있습니다.</div>
  </div>

  <div class="navbar">
    <div class="navbar-inner">
      <ul class="nav">
        <li><%= link_to '최신강의평', lectures_path %></li>
        <li><%= link_to '내가 평가한 강의', lectures_path %></li>
        <li><%= link_to '검색결과', search_lectures_path %></li>
      </ul>
      <%= form_tag search_lectures_path, class: 'navbar-search pull-right' do %>
        <%= text_field_tag :term, '', class: 'search-query', placeholder: '강의명으로 검색하세요' %>
        <%= submit_tag '검색', class: 'btn btn-search' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lectures/search.html.erb
<% if @result.empty? %>
  검색 결과가 없습니다.
<% else %>
<div class="row">
  <% @result.each_with_index do |lecture, i| %>
    <div class="span3">
    <%= render partial: 'shared/lecture', locals: { lecture: lecture } %>
    </div>
    <% if i % 3 == 2 %>
      <div class="clearfix"></div>
    <% end %>
  <% end %>
  <div class="clearfix"></div>
  <%= will_paginate @result, :params => { :query => @query } %>

  <% if current_user.nil? %>
    <%= render :partial => 'shared/not_registered_yet_modal' %>
  <% end %>
</div>
<% end %> 

<div style="clear:both;"></div>

app/views/lectures/show.html.erb
<div class="lecture_info_container">
  <div class="well">
    <div class="pull-left">
      <%= image_tag 'prof.jpg' %>
    </div>
    <div class="pull-left lecture_info">
      <h2><%=@lecture.title %> / <%= @lecture.provider %></h2>
      <p class="pull-left">
      <b>개설학과 </b> <%= @lecture.department %><br/>
      <b>학년 </b> <%= @lecture.level %><br/>
      <b>학점 </b> <%= @lecture.credit %>
    </p>
      <div class="scores pull-left">
        <% if current_user.finished_registration? %>
          <div class="pull-left"><b>강의총점 &nbsp;</b></div>
        <div class="pull-left"><%= star_rating_div(@lecture.overall_score, true, 'overall_score') %></div>
        <div class="clearfix"></div>
        <div class="pull-left"><b>수업만족 &nbsp;</b></div>
        <div class="pull-left"><%= star_rating_div(@lecture.presentation_score, true, 'presentation_score') %></div>
        <div class="clearfix"></div>
        <div class="pull-left"><b>학점만족 &nbsp;</b></div>
        <div class="pull-left"><%= star_rating_div(@lecture.grading_score, true, 'grading_score') %></div>
        <div class="clearfix"></div>
      <% else %>
          <b><%= I18n.t 'assessments.blinded_content' %></b>
      <% end %>

      </div>
      <div class="clearfix"></div>
      <div class="pull-right">
        <a href="#assessment_modal" role="button" class="btn btn-primary" data-toggle="modal">평가하기</a>
        <%= render partial: 'shared/new_assessment_form', locals: { assessment: @assessment, lecture: @lecture } %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div> 
</div>
<div class="assessments_container">
  <% @assessments.each_with_index do |assessment, i| %>
    <% if current_user.finished_registration? %>
        <% if i == 0 %>
          <span class="label label-info">*** 베스트 강의평 ***</span>
        <% end %>
 
      <div class="assessment <%= 'assessment_best' if i == 0 %> well well-small <%= assessment.user_id == current_user.id ? 'mine' : '' %>">
     <div class="pull-left"><b>총점 &nbsp;</b></div>
      <div class="pull-left"><%= star_rating_div(assessment.overall_score, true, 'overall_score') %></div>
      <div class="pull-left"><b>수업만족 &nbsp;</b></div>
      <div class="pull-left"><%= star_rating_div(assessment.presentation_score, true, 'overall_score') %></div>
      <div class="pull-left"><b>학점만족 &nbsp;</b></div>
      <div class="pull-left"><%= star_rating_div(assessment.grading_score, true, 'overall_score') %></div>
      <%= form_for [assessment, Vote.new(positive: false)], html: { class: 'pull-right form-inline vote_form' } do |f| %>
        <%= f.submit '비추 ' + assessment.votes.negative.count.to_s, class: 'btn btn-small btn-danger negative' %>
      <% end %>
      <%= form_for [assessment, Vote.new(positive: true)], html: { class: 'pull-right form-inline vote_form' } do |f| %>
        <%= f.hidden_field :positive %>
        <%= f.submit '추천 ' + assessment.votes.positive.count.to_s, class: 'btn btn-small btn-success positive' %>
      <% end %>
      <div class="clearfix"></div>
      <div class="content">
        <%= c(assessment.content, :user_id => assessment.user_id) %>
      </div>
      <% if assessment.user_id == current_user.id %>
        <div class="pull-right">
          <%= form_for assessment, method: 'post', class: 'form-inline' do |f| %>
            <%= hidden_field_tag :_method, 'delete' %>
            <%= f.submit '삭제하기', class: 'btn btn-link' %>
          <% end %>
        </div>
        <div class="clearfix"></div>
      <% end %>
    </div>
    <% else %>
      <%= I18n.t 'assessments.blinded_content' %>
    <% end %>
  <% end -%>
</div>