config/routes.rb
EwhaNote::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'user_sessions' }

  match 'registrations/edit' => 'registrations#edit'
  match 'registrations/update' => 'registrations#update'

  resources :lectures do
    get :search, on: :collection
    resources :assessments
  end

  resources :assessments do
    get :my, on: :collection
    resources :votes, only: [:create]
  end

  resources :registrations

  root :to => 'assessments#index'

end

app/views/shared/_assessment.html.erb
<div class="assessment">
  <h4>
    <%= link_to assessment.lecture.title, assessment.lecture %>
    <small>[<%= assessment.lecture.provider %>]</small>
  </h4>
  <p>
    <small> <%= c(assessment.content, :user_id => assessment.user_id) %> </small>
  </p>
</div>

<div class="alert alert-info">
  강의총점 <b><%= s(assessment.overall_score, :user_id => assessment.user_id) %></b> |
  수업만족 <b><%= s(assessment.presentation_score, :user_id => assessment.user_id) %></b> |
  과제만족 <b><%= s(assessment.workload_score, :user_id => assessment.user_id) %></b>
</div>

app/views/shared/_lecture.html.erb
<div class="lecture_small">
  <div class="pull-left photo">
    <%= image_tag "prof.jpg"%>
  </div>
  <div class="pull-right content">
    <span class="em_text"><%= link_to lecture.title + " / " + lecture.provider, lecture_path(lecture) %></span>
    <br/>
    <% if current_user && current_user.finished_registration? %>
      <div class="pull-left"><b>강의평점</b></div>
    <div class="pull-left"><%= star_rating_div(lecture.overall_score, true, 'overall_score') %></div>
    <div class="clearfix"></div>
    <div class="pull-left"><b>수업만족</b></div>
    <div class="pull-left"><%= star_rating_div(lecture.presentation_score, true, 'presentation_score') %></div>
    <div class="clearfix"></div>
    <div class="pull-left"><b>학점만족</b></div>
    <div class="pull-left"><%= star_rating_div(lecture.grading_score, true, 'grading_score') %></div>
    <div class="clearfix"></div>
  <% else %>
    <%= I18n.t 'assessments.blinded_content' %>
  <% end %>
  </div>
  <div class="clearfix"></div>
</div>

app/views/shared/_menu.html.erb
<div id="head_wrapper">
  <div id="login_info">
    <%= link_to 'Facebook', 'http://www.facebook.com/SMWUklassmate', class: 'label label-info' %>
    <span class="label label-success"><%= current_user.username %>님 환영합니다.</span>
    <%= link_to '[로그아웃]', destroy_user_session_path, class: '' %>
</div>
  <div id="search_wrapper">
    <a href="/"><div id="head_main_logo"></div></a>
    <div id="total_view"><span id="total_view_number"><%= Assessment.count %></span>&nbsp;개의 강의평이 있습니다.</div>
  </div>

  <div class="navbar">
    <div class="navbar-inner">
      <ul class="nav">
        <li><%= link_to '최신강의평', assessments_path %></li>
        <li><%= link_to '내가 평가한 강의', my_assessments_path %></li>
        <li><%= link_to '검색결과', search_lectures_path %></li>
      </ul>
      <%= form_tag search_lectures_path, method: 'get', class: 'navbar-search pull-right' do %>
        <%= text_field_tag :query, @query, class: 'search-query', placeholder: '강의명으로 검색하세요' %>
        <%= submit_tag '검색', class: 'btn btn-search' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_new_assessment_form.html.erb
<script>

function starClicked(star) {
  var score = 0;
  if(star.className == "one-star") {
    score = 1;
  }
  else if(star.className == "two-stars") {
    score = 2;
  }
  else if(star.className == "three-stars") {
    score = 3;
  }
  else if(star.className == "four-stars") {
    score = 4;
  }
  else if(star.className == "five-stars") {
    score = 5;
  }

  star.parentNode.parentNode.childNodes[0].style.width = score * 30 + "px";
  var container = star.parentNode.parentNode.parentNode
  if(container.id == "overall_score_input") {
    $("#assessment_overall_score").val(score);
  }
  else if(container.id == "presentation_score_input") {
    $("#assessment_presentation_score").val(score);
  }
  else if(container.id == "grading_score_input") {
    $("#assessment_grading_score").val(score);
  }
}

</script>

<div id="assessment_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><%= @lecture.title %> / <%= @lecture.provider %></h3>
  </div>
  <div class="modal-body">
    <%= form_for [@lecture, @assessment] do |f| %>

      <div class="score-input-container">
        <strong>강의평점</strong>
      <%= star_rating_div(1, false, 'overall_score_input') %>
      <%= f.hidden_field :overall_score %>
    </div>

    <div class="score-input-container">
      <strong>수업만족</strong>
      <%= star_rating_div(1, false, 'presentation_score_input') %>
      <%= f.hidden_field :presentation_score %>
    </div>

    <div class="score-input-container">
      <strong>학점만족</strong>
      <%= star_rating_div(1, false, 'grading_score_input') %>
      <%= f.hidden_field :grading_score %>
    </div>

    <h5>주관식 의견</h5>
    <%= f.text_area :content, class: 'assessment', placeholder: '자유롭게 써 주세요', rows: 5 %>
    <%= f.submit '작성하기', class: 'btn btn-primary btn-submit' %>
  <% end %>
  </div>
</div>

app/views/shared/_not_registered_yet_modal.html.erb
<script>
$(window).load(function(){
        $('#not_registered_yet_modal').modal('show');
    });
</script>

<div id="not_registered_yet_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-body">
    <h3>
      명강의를 이용하려면 가입을 하셔야합니다.
    </h3>
      <%= button_to '가입하기!', new_registration_path, method: 'get', class: 'btn btn-primary btn-large btn_join' -%>
  </div>
</div>

app/views/shared/_score.html.erb
<div class="row">
  <div class="span1"><%= label %></div>
  <% score = @lecture.send attribute %>
  <div class="span3">
    <div class="progress progress-striped">
      <div class="bar" style="width: <%= '%.2f' % (score * 10) %>%;">
        <span class="label label-info"><%= '%.1f' % score -%></span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_standings.html.erb
<div class="standings_container">
  <div class="title_container">
    <%= image_tag "standings_title.png" %>
  </div>
  <div class="round_container">
    <table class="standings_table">
      <tbody>
      <tr>
        <th><%= image_tag "gold_medal.png" %></th>
        <td>
          <% if @lectures[0] %>
            <%= link_to @lectures[0].provider + "\n" + "(" + @lectures[0].title + ")", @lectures[0] %>
        <% else %>
            아직 등록되지 않았습니다.
        <% end %>
        </td>
      </tr>
      <tr>
        <th><%= image_tag "silver_medal.png" %></th>
        <td>
          <% if @lectures[1] %>
            <%= link_to @lectures[1].provider + "\n" + "(" + @lectures[1].title + ")", @lectures[1] %>
          <% else %>
              아직 등록되지 않았습니다.
        <% end %>
        </td>
      </tr>
      <tr>
        <th><%= image_tag "bronze_medal.png" %></th>
        <td>
          <% if @lectures[2] %>
            <%= link_to @lectures[2].provider + "\n" + "(" + @lectures[2].title + ")", @lectures[2] %>
        <% else %>
            아직 등록되지 않았습니다.
        <% end %>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div id="user-info-container">
  <%= image_tag 'logo.png' %>

  <div id="user-info">
    <p class="greetings">
      <%= current_user.nickname %>님 환영합니다!
    </p>

    <div class="actions-container">
      <%= link_to 'Logout', destroy_user_session_path, class: 'btn-logout' %>
    </div>
  </div>
</div>