config/routes.rb
EwhaNote::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'user_sessions' }

  match 'registrations/edit' => 'registrations#edit'
  match 'registrations/update' => 'registrations#update'

  resources :lectures do
    get :search, on: :collection
    resources :assessments
  end

  resources :assessments do
    get :my, on: :collection
    resources :votes, only: [:create]
  end

  resources :registrations

  root :to => 'assessments#index'

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < Devise::SessionsController
  def new
    resource = build_resource(nil, :unsafe => true)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end

  def create
    resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    respond_with resource, :location => after_sign_in_path_for(resource)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div id="entrance_container">
  <div class="top_container container">
    <strong>명강의</strong>는 명지대학생만을 위한 강의평가 사이트입니다.
  </div>

  <div class="center_container container">
    <div class="main_logo">
    </div>
    <div class="clearfix"></div>
     <div class="search_bar">
      <%= form_tag search_lectures_path, method: 'get', class: 'form-search' do %>
        <%= text_field_tag :query, @query, class: 'search-query', placeholder: '강의명, 교수명으로 검색하세요' %>
        <%= submit_tag '검색', class: 'btn btn-search btn-inverse' %>
      <% end %>
    </div>
    <div class="login_form_container">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :class => 'form-inline' }) do |f| %>
        <%= f.label :username, 'ID', class: 'control-label' %>
      <%= f.text_field :username, class: 'text_input input-small', placeholder: '' %>
      <%= f.label :password, 'pw', class: 'control-label' %>
      <%= f.password_field :password, class: 'text_input input-small', placeholder: '' %>
      <%= f.submit '로그인', class: 'btn_login' %>
    <% end %>
    </div>
    <div class="restration_container">
      <%= button_to '회원가입', new_registration_path, method: 'get', class: 'btn_join' -%>
      <%= button_to 'ID/비밀번호 찾기', registrations_edit_path, method: 'get', class: 'btn_join' -%>

    </div>
    <div class="clearfix"></div>
  </div>
</div>